application: imartinez-me
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static_site/index.html
  upload: static_site/index.html

- url: /assets
  static_dir: static_site/assets


libraries:
- name: webapp2
  version: "2.5.2"